package com.example.demo.entities;
// Generated 14:49:45 26 thg 9, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Artists generated by hbm2java
 */
@Entity
@Table(name = "artists")
public class Artists implements java.io.Serializable {

	private Integer artistId;
	private String name;
	private String bio;
	private String imageUrl;
	private Date createdAt;
	private Set<Songs> songses = new HashSet<Songs>(0);
	private Set<Follow> follows = new HashSet<Follow>(0);
	private Set<Albums> albumses = new HashSet<Albums>(0);
	private Set<Users> userses = new HashSet<Users>(0);

	public Artists() {
	}

	public Artists(String name, Date createdAt) {
		this.name = name;
		this.createdAt = createdAt;
	}

	public Artists(String name, String bio, String imageUrl, Date createdAt, Set<Songs> songses, Set<Follow> follows,
			Set<Albums> albumses, Set<Users> userses) {
		this.name = name;
		this.bio = bio;
		this.imageUrl = imageUrl;
		this.createdAt = createdAt;
		this.songses = songses;
		this.follows = follows;
		this.albumses = albumses;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "artist_id", unique = true, nullable = false)
	public Integer getArtistId() {
		return this.artistId;
	}

	public void setArtistId(Integer artistId) {
		this.artistId = artistId;
	}

	@Column(name = "name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "bio", length = 65535)
	public String getBio() {
		return this.bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

	@Column(name = "image_url")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "artists")
	public Set<Songs> getSongses() {
		return this.songses;
	}

	public void setSongses(Set<Songs> songses) {
		this.songses = songses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "artists")
	public Set<Follow> getFollows() {
		return this.follows;
	}

	public void setFollows(Set<Follow> follows) {
		this.follows = follows;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "artists")
	public Set<Albums> getAlbumses() {
		return this.albumses;
	}

	public void setAlbumses(Set<Albums> albumses) {
		this.albumses = albumses;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "artists")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
