package com.example.demo.entities;
// Generated 17:38:03 10 thg 9, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Follow generated by hbm2java
 */
@Entity
@Table(name = "follow")
public class Follow implements java.io.Serializable {

	private FollowId id;
	private Artists artists;
	private Users users;
	private Date followedAt;

	public Follow() {
	}

	public Follow(FollowId id, Artists artists, Users users, Date followedAt) {
		this.id = id;
		this.artists = artists;
		this.users = users;
		this.followedAt = followedAt;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "artistId", column = @Column(name = "artist_id", nullable = false)) })
	public FollowId getId() {
		return this.id;
	}

	public void setId(FollowId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "artist_id", nullable = false, insertable = false, updatable = false)
	public Artists getArtists() {
		return this.artists;
	}

	public void setArtists(Artists artists) {
		this.artists = artists;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "followed_at", nullable = false, length = 19)
	public Date getFollowedAt() {
		return this.followedAt;
	}

	public void setFollowedAt(Date followedAt) {
		this.followedAt = followedAt;
	}

}
