package com.example.demo.entities;
// Generated 17:38:03 10 thg 9, 2025 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * FollowId generated by hbm2java
 */
@Embeddable
public class FollowId implements java.io.Serializable {

	private int userId;
	private int artistId;

	public FollowId() {
	}

	public FollowId(int userId, int artistId) {
		this.userId = userId;
		this.artistId = artistId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "artist_id", nullable = false)
	public int getArtistId() {
		return this.artistId;
	}

	public void setArtistId(int artistId) {
		this.artistId = artistId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FollowId))
			return false;
		FollowId castOther = (FollowId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getArtistId() == castOther.getArtistId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getArtistId();
		return result;
	}

}
