package com.example.demo.entities;
// Generated 17:38:03 10 thg 9, 2025 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Genres generated by hbm2java
 */
@Entity
@Table(name = "genres", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Genres implements java.io.Serializable {

	private Integer genreId;
	private String name;
	private Set<Songs> songses = new HashSet<Songs>(0);

	public Genres() {
	}

	public Genres(String name) {
		this.name = name;
	}

	public Genres(String name, Set<Songs> songses) {
		this.name = name;
		this.songses = songses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "genre_id", unique = true, nullable = false)
	public Integer getGenreId() {
		return this.genreId;
	}

	public void setGenreId(Integer genreId) {
		this.genreId = genreId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "genreses")
	public Set<Songs> getSongses() {
		return this.songses;
	}

	public void setSongses(Set<Songs> songses) {
		this.songses = songses;
	}

}
