package com.example.demo.entities;
// Generated 17:38:03 10 thg 9, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * History generated by hbm2java
 */
@Entity
@Table(name = "history")
public class History implements java.io.Serializable {

	private Integer historyId;
	private Songs songs;
	private Users users;
	private Date listenedAt;

	public History() {
	}

	public History(Date listenedAt) {
		this.listenedAt = listenedAt;
	}

	public History(Songs songs, Users users, Date listenedAt) {
		this.songs = songs;
		this.users = users;
		this.listenedAt = listenedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "history_id", unique = true, nullable = false)
	public Integer getHistoryId() {
		return this.historyId;
	}

	public void setHistoryId(Integer historyId) {
		this.historyId = historyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "song_id")
	public Songs getSongs() {
		return this.songs;
	}

	public void setSongs(Songs songs) {
		this.songs = songs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "listened_at", nullable = false, length = 19)
	public Date getListenedAt() {
		return this.listenedAt;
	}

	public void setListenedAt(Date listenedAt) {
		this.listenedAt = listenedAt;
	}

}
