package com.example.demo.entities;
// Generated 17:38:03 10 thg 9, 2025 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * LikesId generated by hbm2java
 */
@Embeddable
public class LikesId implements java.io.Serializable {

	private int userId;
	private int songId;

	public LikesId() {
	}

	public LikesId(int userId, int songId) {
		this.userId = userId;
		this.songId = songId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "song_id", nullable = false)
	public int getSongId() {
		return this.songId;
	}

	public void setSongId(int songId) {
		this.songId = songId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LikesId))
			return false;
		LikesId castOther = (LikesId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getSongId() == castOther.getSongId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getSongId();
		return result;
	}

}
