package com.example.demo.entities;
// Generated 17:38:03 10 thg 9, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Likes generated by hbm2java
 */
@Entity
@Table(name = "likes")
public class Likes implements java.io.Serializable {

	private LikesId id;
	private Songs songs;
	private Users users;
	private Date likedAt;

	public Likes() {
	}

	public Likes(LikesId id, Songs songs, Users users, Date likedAt) {
		this.id = id;
		this.songs = songs;
		this.users = users;
		this.likedAt = likedAt;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "songId", column = @Column(name = "song_id", nullable = false)) })
	public LikesId getId() {
		return this.id;
	}

	public void setId(LikesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "song_id", nullable = false, insertable = false, updatable = false)
	public Songs getSongs() {
		return this.songs;
	}

	public void setSongs(Songs songs) {
		this.songs = songs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "liked_at", nullable = false, length = 19)
	public Date getLikedAt() {
		return this.likedAt;
	}

	public void setLikedAt(Date likedAt) {
		this.likedAt = likedAt;
	}

}
