package com.example.demo.entities;
// Generated 17:38:03 10 thg 9, 2025 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * PlaylistsongsId generated by hbm2java
 */
@Embeddable
public class PlaylistsongsId implements java.io.Serializable {

	private int playlistId;
	private int songId;

	public PlaylistsongsId() {
	}

	public PlaylistsongsId(int playlistId, int songId) {
		this.playlistId = playlistId;
		this.songId = songId;
	}

	@Column(name = "playlist_id", nullable = false)
	public int getPlaylistId() {
		return this.playlistId;
	}

	public void setPlaylistId(int playlistId) {
		this.playlistId = playlistId;
	}

	@Column(name = "song_id", nullable = false)
	public int getSongId() {
		return this.songId;
	}

	public void setSongId(int songId) {
		this.songId = songId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlaylistsongsId))
			return false;
		PlaylistsongsId castOther = (PlaylistsongsId) other;

		return (this.getPlaylistId() == castOther.getPlaylistId()) && (this.getSongId() == castOther.getSongId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlaylistId();
		result = 37 * result + this.getSongId();
		return result;
	}

}
