package com.example.demo.entities;
// Generated 17:38:03 10 thg 9, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Playlistsongs generated by hbm2java
 */
@Entity
@Table(name = "playlistsongs")
public class Playlistsongs implements java.io.Serializable {

	private PlaylistsongsId id;
	private Playlists playlists;
	private Songs songs;
	private Date addedAt;

	public Playlistsongs() {
	}

	public Playlistsongs(PlaylistsongsId id, Playlists playlists, Songs songs, Date addedAt) {
		this.id = id;
		this.playlists = playlists;
		this.songs = songs;
		this.addedAt = addedAt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "playlistId", column = @Column(name = "playlist_id", nullable = false)),
			@AttributeOverride(name = "songId", column = @Column(name = "song_id", nullable = false)) })
	public PlaylistsongsId getId() {
		return this.id;
	}

	public void setId(PlaylistsongsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "playlist_id", nullable = false, insertable = false, updatable = false)
	public Playlists getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Playlists playlists) {
		this.playlists = playlists;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "song_id", nullable = false, insertable = false, updatable = false)
	public Songs getSongs() {
		return this.songs;
	}

	public void setSongs(Songs songs) {
		this.songs = songs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "added_at", nullable = false, length = 19)
	public Date getAddedAt() {
		return this.addedAt;
	}

	public void setAddedAt(Date addedAt) {
		this.addedAt = addedAt;
	}

}
