package com.example.demo.entities;
// Generated 13:13:29 17 thg 10, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Playlists generated by hbm2java
 */
@Entity
@Table(name = "playlists")
public class Playlists implements java.io.Serializable {

	private Integer playlistId;
	private Users users;
	private String name;
	private String description;
	private String coverUrl;
	private Boolean isPublic;
	private Date createdAt;
	private String coverImage;
	private Set<Playlistsongs> playlistsongses = new HashSet<Playlistsongs>(0);

	public Playlists() {
	}

	public Playlists(String name, Date createdAt, String coverImage) {
		this.name = name;
		this.createdAt = createdAt;
		this.coverImage = coverImage;
	}

	public Playlists(Users users, String name, String description, String coverUrl, Boolean isPublic, Date createdAt,
			String coverImage, Set<Playlistsongs> playlistsongses) {
		this.users = users;
		this.name = name;
		this.description = description;
		this.coverUrl = coverUrl;
		this.isPublic = isPublic;
		this.createdAt = createdAt;
		this.coverImage = coverImage;
		this.playlistsongses = playlistsongses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "playlist_id", unique = true, nullable = false)
	public Integer getPlaylistId() {
		return this.playlistId;
	}

	public void setPlaylistId(Integer playlistId) {
		this.playlistId = playlistId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "cover_url")
	public String getCoverUrl() {
		return this.coverUrl;
	}

	public void setCoverUrl(String coverUrl) {
		this.coverUrl = coverUrl;
	}

	@Column(name = "is_public")
	public Boolean getIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(Boolean isPublic) {
		this.isPublic = isPublic;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "cover_Image", nullable = false, length = 65535)
	public String getCoverImage() {
		return this.coverImage;
	}

	public void setCoverImage(String coverImage) {
		this.coverImage = coverImage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "playlists")
	public Set<Playlistsongs> getPlaylistsongses() {
		return this.playlistsongses;
	}

	public void setPlaylistsongses(Set<Playlistsongs> playlistsongses) {
		this.playlistsongses = playlistsongses;
	}

	
}
