package com.example.demo.entities;
// Generated 14:49:45 26 thg 9, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Songs generated by hbm2java
 */
@Entity
@Table(name = "songs")
public class Songs implements java.io.Serializable {

	private Integer songId;
	private Albums albums;
	private Users users;
	private String title;
	private Integer duration;
	private String filePath;
	private String lyrics;
	private Date releaseDate;
	private String imageUrl;
	private String status;
	private Integer listenCount;
	private Date createdAt;
	private Set<Artists> artists = new HashSet<Artists>(0);
	private Set<History> histories = new HashSet<History>(0);
	private Set<Playlistsongs> playlistsongses = new HashSet<Playlistsongs>(0);
	private Set<Genres> genreses = new HashSet<Genres>(0);
	private Set<Likes> likeses = new HashSet<Likes>(0);

	public Songs() {
	}

	public Songs(String title, String filePath, String imageUrl, Date createdAt) {
		this.title = title;
		this.filePath = filePath;
		this.imageUrl = imageUrl;
		this.createdAt = createdAt;
	}

	public Songs(Albums albums, Users users, String title, Integer duration, String filePath, String lyrics,
			Date releaseDate, String imageUrl, String status, Integer listenCount, Date createdAt, Set<Artists> artists,
			Set<History> histories, Set<Playlistsongs> playlistsongses, Set<Genres> genreses, Set<Likes> likeses) {
		this.albums = albums;
		this.users = users;
		this.title = title;
		this.duration = duration;
		this.filePath = filePath;
		this.lyrics = lyrics;
		this.releaseDate = releaseDate;
		this.imageUrl = imageUrl;
		this.status = status;
		this.listenCount = listenCount;
		this.createdAt = createdAt;
		this.artists = artists;
		this.histories = histories;
		this.playlistsongses = playlistsongses;
		this.genreses = genreses;
		this.likeses = likeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "song_id", unique = true, nullable = false)
	public Integer getSongId() {
		return this.songId;
	}

	public void setSongId(Integer songId) {
		this.songId = songId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "album_id")
	public Albums getAlbums() {
		return this.albums;
	}

	public void setAlbums(Albums albums) {
		this.albums = albums;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uploaded_by")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "title", nullable = false, length = 150)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "file_path", nullable = false, columnDefinition = "TEXT")
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "lyrics", length = 65535)
	public String getLyrics() {
		return this.lyrics;
	}

	public void setLyrics(String lyrics) {
		this.lyrics = lyrics;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "release_date", length = 10)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "image_url", nullable = false, length = 65535)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "status", length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	@Column(name = "listen_count")
	public Integer getListenCount() {
		return this.listenCount;
	}

	public void setListenCount(Integer listenCount) {
		this.listenCount = listenCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "song_artists", joinColumns = {
			@JoinColumn(name = "song_id", nullable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "artist_id", nullable = false) })
	public Set<Artists> getartists() {
		return this.artists;
	}

	public void setartists(Set<Artists> artists) {
		this.artists = artists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "songs")
	public Set<History> getHistories() {
		return this.histories;
	}

	public void setHistories(Set<History> histories) {
		this.histories = histories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "songs")
	public Set<Playlistsongs> getPlaylistsongses() {
		return this.playlistsongses;
	}

	public void setPlaylistsongses(Set<Playlistsongs> playlistsongses) {
		this.playlistsongses = playlistsongses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "songgenres", joinColumns = {
			@JoinColumn(name = "song_id", nullable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "genre_id", nullable = false) })
	public Set<Genres> getGenreses() {
		return this.genreses;
	}

	public void setGenreses(Set<Genres> genreses) {
		this.genreses = genreses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "songs")
	public Set<Likes> getLikeses() {
		return this.likeses;
	}

	public void setLikeses(Set<Likes> likeses) {
		this.likeses = likeses;
	}

}
