package com.example.demo.entities;
// Generated 14:49:45 26 thg 9, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", uniqueConstraints = { @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "username") })
public class Users implements java.io.Serializable {

	private Integer userId;
	private String username;
	private String email;
	private String password;
	private String fullName;
	private String avatarUrl;
	private String role;
	private Date createdAt;
	private Set<Follow> follows = new HashSet<Follow>(0);
	private Set<Songs> songses = new HashSet<Songs>(0);
	private Set<Likes> likeses = new HashSet<Likes>(0);
	private Set<Artists> artists = new HashSet<Artists>(0);
	private Set<History> histories = new HashSet<History>(0);
	private Set<Playlists> playlistses = new HashSet<Playlists>(0);

	public Users() {
	}

	public Users(String username, String email, String password, Date createdAt) {
		this.username = username;
		this.email = email;
		this.password = password;
		this.createdAt = createdAt;
	}

	public Users(String username, String email, String password, String fullName, String avatarUrl, String role,
			Date createdAt, Set<Follow> follows, Set<Songs> songses, Set<Likes> likeses, Set<Artists> artists,
			Set<History> histories, Set<Playlists> playlistses) {
		this.username = username;
		this.email = email;
		this.password = password;
		this.fullName = fullName;
		this.avatarUrl = avatarUrl;
		this.role = role;
		this.createdAt = createdAt;
		this.follows = follows;
		this.songses = songses;
		this.likeses = likeses;
		this.artists = artists;
		this.histories = histories;
		this.playlistses = playlistses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "username", unique = true, nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email", unique = true, nullable = false, length = 150)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "full_name", length = 150)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "avatar_url")
	public String getAvatarUrl() {
		return this.avatarUrl;
	}

	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	@Column(name = "role", length = 5)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Follow> getFollows() {
		return this.follows;
	}

	public void setFollows(Set<Follow> follows) {
		this.follows = follows;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Songs> getSongses() {
		return this.songses;
	}

	public void setSongses(Set<Songs> songses) {
		this.songses = songses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Likes> getLikeses() {
		return this.likeses;
	}

	public void setLikeses(Set<Likes> likeses) {
		this.likeses = likeses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "userartists", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "artist_id", nullable = false) })
	public Set<Artists> getartists() {
		return this.artists;
	}

	public void setartists(Set<Artists> artists) {
		this.artists = artists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<History> getHistories() {
		return this.histories;
	}

	public void setHistories(Set<History> histories) {
		this.histories = histories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Playlists> getPlaylistses() {
		return this.playlistses;
	}

	public void setPlaylistses(Set<Playlists> playlistses) {
		this.playlistses = playlistses;
	}

}
